# Pre-commit git hooks.
#
# Usage:
#   1. Run one of:
#     $ pip install pre-commit
#     $ brew install pre-commit
#
#   2. Install hooks
#     $ pre-commit install
#
#   3. Optionally, enable automatic updates
#     $ pre-commit autoupdate
default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
