name: Lint (flake8)

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Get changed python files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: "**/*.py"

      - name: Install flake8 and isort
        run: pip install flake8 isort

      - name: flake8 changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          flake8 ${{ steps.changed-files.outputs.all_changed_files }}

      - name: isort changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          set +e
          isort --check --diff ${{ steps.changed-files.outputs.all_changed_files }}
          exit_code="${?}"
          if [[ "${exit_code}" -ne 0 ]]; then
            git diff --color
            exit "${exit_code}"
          fi